/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pq4;

import conexionbd.pq1.Conexion;
import java.awt.Dimension;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JProgressBar;

/**
 *
 * @author santiagob20
 */
public class JFInicial extends javax.swing.JFrame {

    /**
     * Creates new form JFInicial
     */
    int num=0;
    
    static JFInicial jf= new JFInicial();
    
    
//    JProgressBar current = new JProgressBar(0, 2000);
    public int iterate() {
    while (num < 500) {
      current.setValue(num);
      try {
        Thread.sleep(100);
      } catch (InterruptedException e) {
      }
      num += 95;
    }
    return 1;
    
  }
    
     
    
    
    public JFInicial() {
        initComponents();
        this.setSize(new Dimension(705, 391));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        current = new javax.swing.JProgressBar();
        btnContinuar = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(current);
        current.setBounds(280, 250, 146, 20);

        btnContinuar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pq4/Imagenes/btn_next.png"))); // NOI18N
        btnContinuar.setBorderPainted(false);
        btnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarActionPerformed(evt);
            }
        });
        getContentPane().add(btnContinuar);
        btnContinuar.setBounds(280, 280, 150, 40);

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pq4/Imagenes/inicial.png"))); // NOI18N
        getContentPane().add(Fondo);
        Fondo.setBounds(0, 0, 705, 385);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarActionPerformed
        // TODO add your handling code here:
        Conexion c = new Conexion();
        c.conectarse();
        ResultSet rs = null;
        PreparedStatement st;
        try 
        {
            st = Conexion.c.prepareStatement("SELECT * FROM equipos where codigo=1");
            rs = st.executeQuery();
        } 
        catch (SQLException ex) 
        {
            Logger.getLogger(JFInicial.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            if (rs.next())
            {
                jf.iterate();
                jf.setVisible(false);
                JFPrincipal jfc = new JFPrincipal();
                jfc.setVisible(true);
                
            }
            else
            {
                jf.iterate();
                jf.setVisible(false);
                JFInicial2 jfc = new JFInicial2();
                jfc.setVisible(true);
            }
        } catch (SQLException ex) {
            Logger.getLogger(JFInicial.class.getName()).log(Level.SEVERE, null, ex);
        }

        
    }//GEN-LAST:event_btnContinuarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                jf.setVisible(true);
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton btnContinuar;
    private javax.swing.JProgressBar current;
    // End of variables declaration//GEN-END:variables
}
