/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pq4;

import conexionbd.pq1.Conexion;
import conexionbd.pq1.DAOEquiposImp;
import conexionbd.pq1.DAOPartidosImp;
import java.awt.Dimension;
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author santiagob20
 */
public class JFPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JFPrincipal
     */
    
    static JFPrincipal jf = new JFPrincipal();
    DAOEquiposImp d = new DAOEquiposImp();
    
    public JFPrincipal() {
        initComponents();
        this.setSize(new Dimension(705, 391));
        try {
            
            NombreEquipo();
            Image foto = getToolkit().getImage(d.consultaUrl());
            foto = foto.getScaledInstance(143, 143, Image.SCALE_DEFAULT);
            cjEscudo.setIcon(new ImageIcon(foto));
            
        } catch (SQLException ex) {
            Logger.getLogger(JFPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
   public void setNombreTeam(String name) {
        this.cjNombreTeam.setText(name);
    } 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cjEscudo = new javax.swing.JLabel();
        cjNombreTeam = new javax.swing.JLabel();
        btnPartidosProg = new javax.swing.JButton();
        btnVerEquipo = new javax.swing.JButton();
        btnHistorico = new javax.swing.JButton();
        btnProgPartido = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        cjEscudo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pq4/Imagenes/Fc_barcelona1.png"))); // NOI18N
        getContentPane().add(cjEscudo);
        cjEscudo.setBounds(280, 50, 140, 140);

        cjNombreTeam.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        cjNombreTeam.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cjNombreTeam.setText("Nombre_Equipo");
        getContentPane().add(cjNombreTeam);
        cjNombreTeam.setBounds(250, 190, 200, 40);

        btnPartidosProg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pq4/Imagenes/btn_partidos_prog.png"))); // NOI18N
        btnPartidosProg.setBorderPainted(false);
        btnPartidosProg.setContentAreaFilled(false);
        btnPartidosProg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPartidosProg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPartidosProgActionPerformed(evt);
            }
        });
        getContentPane().add(btnPartidosProg);
        btnPartidosProg.setBounds(530, 290, 150, 50);

        btnVerEquipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pq4/Imagenes/btn_verEquipo.png"))); // NOI18N
        btnVerEquipo.setBorderPainted(false);
        btnVerEquipo.setContentAreaFilled(false);
        btnVerEquipo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVerEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerEquipoActionPerformed(evt);
            }
        });
        getContentPane().add(btnVerEquipo);
        btnVerEquipo.setBounds(20, 290, 150, 50);

        btnHistorico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pq4/Imagenes/btn_hist.png"))); // NOI18N
        btnHistorico.setBorderPainted(false);
        btnHistorico.setContentAreaFilled(false);
        btnHistorico.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHistorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistoricoActionPerformed(evt);
            }
        });
        getContentPane().add(btnHistorico);
        btnHistorico.setBounds(190, 290, 150, 50);

        btnProgPartido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pq4/Imagenes/prog_part.png"))); // NOI18N
        btnProgPartido.setBorderPainted(false);
        btnProgPartido.setContentAreaFilled(false);
        btnProgPartido.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProgPartido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProgPartidoActionPerformed(evt);
            }
        });
        getContentPane().add(btnProgPartido);
        btnProgPartido.setBounds(360, 290, 150, 50);

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pq4/Imagenes/main.png"))); // NOI18N
        getContentPane().add(Fondo);
        Fondo.setBounds(0, 0, 705, 391);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerEquipoActionPerformed
        
         jf.setVisible(false);
        JFVerEquipo jfc = new JFVerEquipo();
        jfc.setVisible(true);
        DAOEquiposImp E = new DAOEquiposImp();
        try 
        {
            E.consultarT();
        } 
        catch (Exception ex) 
        {
            Logger.getLogger(JFPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnVerEquipoActionPerformed

    private void btnHistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoricoActionPerformed
        // TODO add your handling code here:
        DAOPartidosImp p = new DAOPartidosImp();
        
        jf.setVisible(false);
        JFHistorico jfc = new JFHistorico();
        jfc.setVisible(true);
        try {
            p.consultarHistorico();
        } catch (Exception ex) {
            Logger.getLogger(JFPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        
    }//GEN-LAST:event_btnHistoricoActionPerformed

    private void btnProgPartidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProgPartidoActionPerformed
        // TODO add your handling code here:
        jf.setVisible(false);
        JFProgPartido jfc = new JFProgPartido();
        jfc.setVisible(true);
        try {
            NombreEquipo();
        } catch (SQLException ex) {
            Logger.getLogger(JFPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnProgPartidoActionPerformed

    private void btnPartidosProgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPartidosProgActionPerformed
        // TODO add your handling code here:
        DAOPartidosImp p = new DAOPartidosImp();
        
        jf.setVisible(false);
        JFPartidosProg jfc = new JFPartidosProg();
        jfc.setVisible(true);
        try {
            p.consultarProgramados();
        } catch (Exception ex) {
            Logger.getLogger(JFPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPartidosProgActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            public void run() {
                jf.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton btnHistorico;
    private javax.swing.JButton btnPartidosProg;
    private javax.swing.JButton btnProgPartido;
    private javax.swing.JButton btnVerEquipo;
    public static javax.swing.JLabel cjEscudo;
    public static javax.swing.JLabel cjNombreTeam;
    // End of variables declaration//GEN-END:variables

private void NombreEquipo() throws SQLException{
        try
        {
            Conexion cx = new Conexion();
            Connection c =null;
            cx.conectarse();
            PreparedStatement st = Conexion.c.prepareStatement("SELECT equipos.nombre FROM equipos where codigo=1");
            ResultSet rs = st.executeQuery();
            
            while (rs.next()) 
            {
                JFProgPartido.cjEquipo1.setText(rs.getString("nombre"));
                JFPrincipal.cjNombreTeam.setText(rs.getString("nombre"));
                
            }                    
       } 
        catch(SQLException ex)
        {
           throw ex;
       }
        
        
        
    }

   
}

