/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pq4;

import conexionbd.pq1.Conexion;
import static conexionbd.pq1.Conexion.c;
import conexionbd.pq1.DAOPartidosImp;
import java.awt.Dimension;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import pq2.Equipo;
import pq2.Partido;

/**
 *
 * @author santiagob20
 */
public class JFProgPartido extends javax.swing.JFrame {

    /**
     * Creates new form JFProgPartido
     */
   
    static JFProgPartido jf = new JFProgPartido();
    public JFProgPartido() {
        initComponents();
        this.setSize(new Dimension(705, 391));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAtras = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        cjEquipo1 = new javax.swing.JTextField();
        cjEquipoRival = new javax.swing.JTextField();
        cjEstadio = new javax.swing.JTextField();
        cjHoraPartido = new javax.swing.JFormattedTextField();
        cjFechaPartido = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnLocal = new javax.swing.JRadioButton();
        btnVisitante = new javax.swing.JRadioButton();
        cjTMarcRival = new javax.swing.JTextField();
        cjTMarcFavorito = new javax.swing.JTextField();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pq4/Imagenes/btn_atras.png"))); // NOI18N
        btnAtras.setBorderPainted(false);
        btnAtras.setContentAreaFilled(false);
        btnAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(btnAtras);
        btnAtras.setBounds(10, 10, 160, 40);

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pq4/Imagenes/btn_guardar.png"))); // NOI18N
        btnGuardar.setBorderPainted(false);
        btnGuardar.setContentAreaFilled(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar);
        btnGuardar.setBounds(430, 320, 150, 40);

        cjEquipo1.setEditable(false);
        cjEquipo1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cjEquipo1.setText("EquipoFav");
        cjEquipo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cjEquipo1ActionPerformed(evt);
            }
        });
        getContentPane().add(cjEquipo1);
        cjEquipo1.setBounds(120, 130, 130, 30);

        cjEquipoRival.setText("-");
        getContentPane().add(cjEquipoRival);
        cjEquipoRival.setBounds(120, 220, 130, 30);

        cjEstadio.setText("-");
        getContentPane().add(cjEstadio);
        cjEstadio.setBounds(530, 110, 130, 30);

        cjHoraPartido.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance())));
        cjHoraPartido.setText("12:00:00 am");
        getContentPane().add(cjHoraPartido);
        cjHoraPartido.setBounds(530, 210, 130, 30);

        cjFechaPartido.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("M/d/yyyy"))));
        cjFechaPartido.setText("01/01/2000");
        getContentPane().add(cjFechaPartido);
        cjFechaPartido.setBounds(530, 160, 130, 30);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("HORA PARTIDO");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(370, 210, 160, 30);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("VS");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(170, 180, 30, 16);

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ESTADIO");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(440, 110, 90, 30);

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("FECHA PARTIDO");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(370, 160, 160, 30);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("HH:MM:SS am/pm");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(530, 230, 130, 30);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("MM/D/YYYY");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(550, 180, 80, 30);

        btnLocal.setForeground(new java.awt.Color(255, 255, 255));
        btnLocal.setText("Local");
        btnLocal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocalActionPerformed(evt);
            }
        });
        getContentPane().add(btnLocal);
        btnLocal.setBounds(20, 120, 120, 23);

        btnVisitante.setForeground(new java.awt.Color(255, 255, 255));
        btnVisitante.setText("Visitante");
        btnVisitante.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(btnVisitante);
        btnVisitante.setBounds(20, 150, 120, 23);

        cjTMarcRival.setBackground(new java.awt.Color(204, 204, 204));
        cjTMarcRival.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        cjTMarcRival.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cjTMarcRival.setText("0");
        getContentPane().add(cjTMarcRival);
        cjTMarcRival.setBounds(260, 210, 50, 50);

        cjTMarcFavorito.setBackground(new java.awt.Color(204, 204, 204));
        cjTMarcFavorito.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        cjTMarcFavorito.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cjTMarcFavorito.setText("0");
        getContentPane().add(cjTMarcFavorito);
        cjTMarcFavorito.setBounds(260, 120, 50, 50);

        Fondo.setForeground(new java.awt.Color(255, 255, 255));
        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pq4/Imagenes/subpanel.png"))); // NOI18N
        Fondo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(Fondo);
        Fondo.setBounds(0, 0, 704, 390);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try {
            // TODO add your handling code here:
             String ab="01/01/2000";
             String b="";
            if(ab.equals(cjFechaPartido.getText())||b.equals(cjFechaPartido.getText())){
                JOptionPane.showMessageDialog(null, "Informacion Errada", "Error", JOptionPane.ERROR_MESSAGE);
            }else{
               guardar();  
            }
           
        }catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Informacion Errada", "Error", JOptionPane.ERROR_MESSAGE);
            }
        jf.setVisible(false);
        JFPrincipal jfc = new JFPrincipal();
        jfc.setVisible(true);
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLocalActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        // TODO add your handling code here:
        jf.setVisible(false);
        JFPrincipal jfc = new JFPrincipal();
        jfc.setVisible(true);
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void cjEquipo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cjEquipo1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cjEquipo1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFProgPartido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFProgPartido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFProgPartido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFProgPartido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                jf.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JRadioButton btnLocal;
    private javax.swing.JRadioButton btnVisitante;
    public static javax.swing.JTextField cjEquipo1;
    private javax.swing.JTextField cjEquipoRival;
    private javax.swing.JTextField cjEstadio;
    private javax.swing.JFormattedTextField cjFechaPartido;
    private javax.swing.JFormattedTextField cjHoraPartido;
    private javax.swing.JTextField cjTMarcFavorito;
    private javax.swing.JTextField cjTMarcRival;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables

    private void guardar() throws Exception 
    {
        try 
        {
            Partido p = new Partido();
            DAOPartidosImp pr = new DAOPartidosImp();
            p.setEquipoFav(cjEquipo1.getText());
            p.setMarcadorFav(Integer.parseInt(cjTMarcFavorito.getText()));
            
            if(btnLocal.isSelected()==true)
            {
               p.setTipoFav("Local");
               p.setTipoRival("Visitante");
            }else if(btnVisitante.isSelected()==true)
            {
             p.setTipoFav("Visitante");
             p.setTipoRival("Local");
            }
            
            p.setEquipoRival(cjEquipoRival.getText());
            p.setMarcadorRival(cjTMarcRival.getText());
            p.setEstadio(cjEstadio.getText());
            p.setFecha(cjFechaPartido.getText());
            p.setHora(cjHoraPartido.getText());
            
            pr.agregarPartido(p);
            JOptionPane.showMessageDialog(null,"Partido guardado exitosamente", "Informacion", JOptionPane.INFORMATION_MESSAGE);
        } 
            catch (SQLException ex) 
        {
            JOptionPane.showMessageDialog(null, "Error SQL");
        }
    
    }






}
